# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zach Barnes | Portfolio
author: Zach Barnes
email: Zacharias3690@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front End Developer focused on architecture, UI Frameworks and web applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ztbarnes.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Zacharias3690
linkedin_username: zachbarnes
google_analytics: UA-59781543-2

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
navigation:
  - text: Home
    url: /
  - text: Resume
    url: /resume/
  - text: Blog
    url: /blog/
  - text: Projects
    url: /projects/
projects:
  - name: Skip
    url: https://www.skip.dating/
    image: /assets/images/skip_logo.png
    alt: Skip Logo
  - name: Thread
    url: https://github.com/Zacharias3690/Thread
    image: /assets/images/thread.png
    alt: Thread Logo
  - name: King's Cup
    url: https://github.com/Zacharias3690/KingsCup
  - name: Vuex Action Logger
    url: https://github.com/Zacharias3690/vuex-action-logger
  - name: Portfolio
    url: https://github.com/Zacharias3690/Portfolio
  - name: TC-Grid
    url: https://github.com/ThirdCornerLLC/tc-grid
blogs:
  - name: My First Portfolio Design as a Developer
    description: Every developer who has attempted to fill a blank screen will tell you, it’s hard. I’ve spent years telling designers no, suggesting changes, and modifying existing designs, but coming up with something all by myself was one of the hardest tasks I’ve undergone.
    url: https://medium.com/@zacharias3690/my-first-portfolio-design-as-a-developer-8a183877eee5
    image: https://cdn-images-1.medium.com/max/256/1*Cszbi5pVwjfvvQhfzUSaZg.png
    alt: Portfolio image
